name: 'LearnGo'
services:
  postgres:
    image: harbor.jandzsogyorgy.hu/docker/postgres:16.2
    environment:
      - "TZ=Europe/Budapest"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=12345678"
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

  initdb:
    image: harbor.jandzsogyorgy.hu/ghcr/onedr0p/postgres-init:16.2
    environment:
      - "TZ=Europe/Budapest"
      - "INIT_POSTGRES_HOST=postgres"
      - "INIT_POSTGRES_SUPER_PASS=12345678"
      - "INIT_POSTGRES_DBNAME=learn_go"
      - "INIT_POSTGRES_USER=learn_go"
      - "INIT_POSTGRES_PASS=12345678"
